# When to run 
trigger: none  # manual
pr:
- dev
- conflict

pool:
  vmImage: ubuntu-latest

steps:
- bash: ls -a | grep -i 'Dev-Branch-Specific'
  displayName: Verify If we're in Dev Branch
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -n demo-pipeline -l westus'
