# When to run 
trigger: none  # manual
pr:
- main
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -n demo-pipeline -l westus'
