trigger: none

pool:
  vmImage: ubuntu-latest
#========================================
variables:
- name: SUB
  value: "f7112303-c341-437d-bc39-3cd87dfd6fb7"
- name: DIR
  value: "labs/codes/oidc"
# ================================================

steps:
# - task: AzureKeyVault@2
#   inputs:
#     azureSubscription: 'oidc'
#     KeyVaultName: 'ts76'
#     SecretsFilter: '*'
#     RunAsPreJob: true
- task: AzureCLI@2
  name: set_variables
  displayName: set terraform credentials
  inputs:
    azureSubscription: 'oidc'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
      Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$env:idToken"
      Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
      Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
      Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
      terraform init
      terraform plan
    addSpnToEnvironment: true
    workingDirectory: $(DIR)
  env:
    ARM_SUBSCRIPTION_ID: $(SUB)

- task: AzureCLI@2
  name: apply
  displayName: apply
  inputs:
    azureSubscription: 'oidc'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform apply --auto-approve'
    addSpnToEnvironment: true
    workingDirectory: $(DIR)
  env:
    ARM_SUBSCRIPTION_ID: $(SUB)
